### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#34]
We should move to the latest version of wagmi, monitor the number of requests we are issuing and check with walletconnect why we see this error.

![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/fce28f55-2ab6-4e8c-871e-6c52e946d184)

Strangely, our API usage in cloud.walletconnect.com is 0 despite the url having the correct project id in its requests:

![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/45c559f7-435b-416b-aa10-888282cf30b1)

It also looks like some requests connect to cloudflare-eth.com, which is the default provider for viem, which is often used in concert with wagmi, but apparently requires its own configuration.

**Comment by samclassix** [comment]
### These are my discoveries so far
Currently, there are some adverse side-effects associated with fetching data or making API calls within React components. React components should "primarily" focus on rendering and remain detached from such tasks. Whenever React refreshes a component that implements data fetching or API calls, it automatically triggers these actions, leading to potential issues. At a certain scale, Wagmi encountered a '429 Too Many Requests' error response. As a workaround, it switched to the backup service provided by cloudflare-eth.com, attempting to request the same data as before.

### When might our data have changed?
Given our reliance on the Ethereum blockchain, any relevant changes to our data could occur with each new block.

Wagmi implements a roughly 5sec fetching interval for the latest block height (eth_blockNumber):

![Screenshot 2024-05-11 at 8 58 14 AM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/c1b6e5a1-616f-49b6-aee8-b9b186b70e6d)

```
{
    "jsonrpc": "2.0",
    "id": 548, // request id
    "method": "eth_blockNumber"
}
```

#### Component called BlockUpdater
To stay updated with the latest block height changes, let's introduce a new component called BlockUpdater. This component will execute a one-time solution for fetching new block states for the application, employing either a Full Update or Lazy Loading approach.

```
import { useBlockNumber } from "wagmi";
import { useEffect } from "react";

export default function BockUpdater() {
  const {error, data} = useBlockNumber();

  useEffect(() => {
    if (error) return
    console.log(`New block found: ${data}`);
    // call redux slice A fetch
    // call redux slice B fetch
    // call redux slice C fetch
    // call redux slice D fetch
   }, [error, data])

  return <></>;
}
```

### Get state from store
Each component requiring access to the Redux store retrieves data from the store or slices using the useSelector hook and object tree parameter. e.g.:

```
import React from 'react'
import { useSelector } from 'react-redux'

export function Counter() {
  const count = useSelector(state => state.counter.value)
...
```

### We could consider following steps:
- Implement Redux Store - A store holds the whole [state tree](https://redux.js.org/understanding/thinking-in-redux/glossary#state) of your application. (https://redux.js.org/api/store)
- Implement Redux Slices - The state produced by combineReducers() namespaces the states of each reducer under their keys [...] (https://redux.js.org/api/combinereducers#state-slices)
- Remove/Detache data fetching from components and rely on the Redux Store for state rendering
- Each component needs to access the Redux state and refrain from directly pulling data within itself. Transition to global state management rather than component-specific states.

## Those changes will eliminate the constant and unnecessary fetching of data, which is highly likely to have remained unchanged.

**Comment by samclassix** [comment]
## Update

- Extended Ponder Backend for positions indexing. 
- Integrated Redux Store in dApp
- Integration Redux Slice for positions, 1 request via apollo-client (no-hook)
  - filter, open, closed, denied, original/clones, collateral

![Screenshot 2024-05-16 at 6 29 52 PM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/dc3d236f-9a7a-4a29-8d6b-b3af1c7df410)

![Screenshot 2024-05-16 at 6 31 46 PM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/61398be4-cd37-430e-932a-a3d996412068)

- Integration Redux Slice for prices (ERC20Info type with coingecko data, UPSET policy)

![Screenshot 2024-05-16 at 6 31 02 PM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/5a60df17-a59b-4ffc-95d1-585982bcea71)

- Init Redux Slice for Account, used for user address, account data, allowance, ...
- Implementation of BlockUpdater component
- Implementing of BlockUpdater policies, address changes, ERC20Infos changes, each block, 10 blocks, 100 blocks
- UPSET: no overwriting, create or update policy, only dispatch and update state if changed

#### EACH BLOCK Update Policy
- upset positions
- upset account data, if address is defined

#### 10 BLOCKS Update Policy
- upset coingecko prices

#### ERC20Infos 
aka. all relevant ERC20 token addresses
atm: all mintable (ZCHF), all collateral token used in positions
- upset ER20Infos
- triggers -> prices updates

#### ADDRESS CHANGES Update Policy
- upset account data

## Improvement

#### Before
- sometimes hundreds requests
   - requesting the same data
   - requesting data which didnt change again
   - react render management for components which fetches data triggered in a component
- components trigger data fetch
- too many requests error message

#### After
- 1 request per block, via BlockUpdater, to own Ponder Indexer Service
- fetches all position data at once, due to extending Ponder Indexer Service
- 1 request per block, for account data (NOT READY YET), via Ponder Indexer or SmartContract calls
- 6 request per 10 blocks, for coingecko data, upset policy


## Improvements and performance improvements are enormously!

- Have a look at the network traffic (timing scale)
- Most of the times just fetching "eth_blockNumber"
- Just 6 requests to coingecko (can be also just ONE, but free tier doesn't allow)

<img width="872" alt="Screenshot 2024-05-16 at 6 43 56 PM" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/7a0c34fa-76dd-493f-95e4-d0831c4f1d35">


## Positions filtered by collateral and originals
No need to fetch data at the positions page, and you have access to all position data stored in the redux store.

- Open Positions By Collateral (Best for overview)
- Open Positions By Originals (Best for circular dependency between originals and clones)
 - Original
   - Clone A
   - Clone B
   - Clone C
   - ... 

<img width="1250" alt="Screenshot 2024-05-16 at 6 08 18 PM" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/858003a2-8c59-43a6-bfc6-aa12424ba498">

**Comment by samclassix** [comment]
## Network Traffic over time

- 25min time frame
- constant request flow, due to controlled requesting updates
- ca. 150kB transferred
- 6 requests to coingecko only

<img width="803" alt="Screenshot 2024-05-16 at 7 08 37 PM" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/f9a7e45d-3f10-49d6-82bc-8ca4217196a9">

**Comment by samclassix** [comment]
## Controlled Fetching and Enforced Update Policies

<img width="573" alt="Screenshot 2024-05-16 at 7 16 43 PM" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/651dcfda-ba0b-463e-96e1-af716f518555">

**Comment by samclassix** [comment]
should be solved with current state of dev branch. As soon its stable and testing went well, it should be applied to main to stop flooding with requests until the api access key limits are exhausted. If limits are reached, testing on dev does not work neither, because the main and dev applications share the same api keys. @luziusmeisser can we have a separate walletconnect api for dev namespace, it would improve development and testing by separating both namespaces also with api key. Also good for tracking.

**Comment by luziusmeisser** [comment]
Maybe we should move all api calls to alchemy so we have all the stats in one place?
Feel free to setup different keys there (production frontend, dev frontend, production ponder, dev ponder).
