### ISSUE TITLE
Easy UI when proposing & minor bugs

### ISSUE THREAD

**Issue by AndreasFC94** [Frankencoin-ZCHF/frankencoin-dapp#42]
When proposing a new position, I should be able to see how many ZCHF I'll be able to mint. This should be a dynamic change, meaning it should change as I change the proposed collateral amount, and it should include all additional cost. 

The "Approve Handling of (token)" button doesn't react when no wallet is connected; This should open a dialogue field explaining that a wallet needs to be connected first. 

Adjust site suggestion of spending cap to Metamask. Example: Current suggested spending cap when there is no balance of the corresponding token is broken.

**Comment by luziusmeisser** [comment]
These are three issues. Please open separate tasks for each of them, ideally accompanied by a screenshot.

For the first, it would be great to have a screenshot where you can indicate what exactly you would expect where to appear. This is too vague to be actionable.

The second one seems actionable, but would also benefit from a screenshot and a URL to the place where exactly this happened.

The third one lacks a specification what is broken. Good bug reports should always describe the current behavior and the expected behavior. For example: "when there is no balance, it proposes a spending cap of 0, but I actually expected it to propose a spending cap of 113."
