### ISSUE TITLE
not possible to sell FPS

### ISSUE THREAD

**Issue by Lalaars** [Frankencoin-ZCHF/frankencoin-dapp#78]
Hello,

since last week I have been trying to exchange my FPS back into ZCHF. I have enough gas fees on the wallet and still my order is not executed. I don't know what to do.

Unfortunately, I have blocked myself from your group on Telegram after I slipped in the line during the math problem.

Can you please help me? 

Best regards
Lars

**Comment by luziusmeisser** [comment]
Clsoing because cannot reproduce. We need more information to be able to answer to such a request. Feel free to reopen if the problem persists.

Do you have mainnet or polygon FPS? Do you have FPS or WFPS? Did you sign a transaction in your wallet? Can you post a sceenshot? Does the UI show en arror? etc.
