### ISSUE TITLE
Cookie depreciation warning

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#79]
Chrome warns me that the site is using third party cookies that will not be supported any more in the future:
![image](https://github.com/user-attachments/assets/94ea110e-c33a-4964-abf5-671f09abce58)

Is that from wallet connect? Would be good to know which part of our app might fail in the future.

**Comment by samclassix** [comment]
To be honest, i don't get any third-party cookie warning. And it should not be related to wallet connect, because it uses the projectId for references, right?

**Comment by luziusmeisser** [comment]
Wallet connect uses cookies to remember the users wallet address, so that when you visit the page again, you are already "connected".

**Comment by samclassix** [comment]
# My observations. 
(in general i use Brave Browser). 

## Blocking all cookies
![Screenshot 2024-07-26 at 1 43 23 PM](https://github.com/user-attachments/assets/8b850c40-8e95-4031-8a9c-9bf6b657219c)

## App does not load
![Screenshot 2024-07-26 at 1 43 49 PM](https://github.com/user-attachments/assets/fcf18939-7a94-457e-9679-93551e59206a)

## Blocking just third-party cookies, but app loads also without third-party cookies
![Screenshot 2024-07-26 at 1 44 04 PM](https://github.com/user-attachments/assets/a746e841-631d-483a-a382-911600281dc9)

I will have an eye on this. And will do some checks in the future

**Comment by samclassix** [comment]
# Quick Solution for closing this issue
As soon:
- you decide to block third party cookies 
- browser's slowly upgrade to as the default behavior

the app won't load or work anymore, most likely due to WalletConnect. Added a message to make aware that this could be the reason the app doesnt work.

# Desktop
<img width="1220" alt="Screenshot 2024-08-14 at 12 20 21 PM" src="https://github.com/user-attachments/assets/ac30f1aa-806f-4760-a6b0-01c1296f7a23">


# Mobile
![localhost_3000_mypositions(iPhone XR)](https://github.com/user-attachments/assets/0565ff1c-058e-4fed-9f46-ac876f0ef2bd)

**Comment by samclassix** [comment]
# Other webpages start displaying a waring as well
![Screenshot 2024-08-15 at 9 11 51 AM](https://github.com/user-attachments/assets/7091bce0-e93e-4ef6-bb06-81bd7a547c1d)
