### ISSUE TITLE
Governance Page Updates

### ISSUE THREAD

**Issue by samclassix** [Frankencoin-ZCHF/frankencoin-dapp#86]
# Ready for review. PR #114 

> Live under app.test...
> Chain: Polygon, test deployment
> Link: https://app.test.frankencoin.com/governance

# What i discovered in the voters table

The table data comes from hooks not a state, if you do a tx like "delegate" or "revoke", changes won't trigger a react re-render of components.

```
import { useFPSHolders } from "@hooks";
import { useVotingPowers } from "@hooks";
...
const fpsHolders = useFPSHolders();
const votingPowersHook = useVotingPowers(fpsHolders.holders);
```

React will not re-render if state changes, because its a hook and must stay "unconditional" under react components.

Basically, what i did the last months with the app is, to reduce or exclude hooks and rewrote them via a redux state coming from the api. Which gives each property of the state similar abilities like a "useState" side-effect. This is achievable by using the "useSelector" to reach a state from the redux store. React will re-render any changes from the state automatically. 

# What i could do

- include the votingPower mapping in the api
- fetch ponder indexing
- prepare mapping and calculations at the api service layer
- export "ready to use" state with an Endpoint from the api
- include votingPower as a state in redux
- exclude the use of hooks and rely on redux state

# We could also just leave it as it is

- we don't delegate forth and back
- we can just navigate back to the governance page, to see the new state. 
- (aka manual triggering a re-render)

**Comment by AndreasFC94** [comment]
Latest mock-up (split into two for better readability): 

![kuva](https://github.com/user-attachments/assets/343dba99-d1e2-48a7-8526-0edc338d7ebc)
![kuva](https://github.com/user-attachments/assets/df098823-276d-422c-8a71-af6dd7eed8b7)

**Comment by samclassix** [comment]
done. PR #114

**Comment by samclassix** [comment]
![Screenshot 2024-08-29 at 6 18 22 PM](https://github.com/user-attachments/assets/771f28e8-6495-4e20-82ee-84f2d2ab62a1)
![Screenshot 2024-08-29 at 6 18 31 PM](https://github.com/user-attachments/assets/5e7009f4-894d-4a46-9e6d-8eed337f4b13)
![Screenshot 2024-08-29 at 6 18 35 PM](https://github.com/user-attachments/assets/f75319b9-35d7-4187-815d-770acb383a88)
![Screenshot 2024-08-29 at 6 18 16 PM](https://github.com/user-attachments/assets/baef3a97-e4fa-4b83-b9d6-7c043161e92d)

**Comment by luziusmeisser** [comment]
For the FPS holder section, I would change the following:

<img width="856" alt="image" src="https://github.com/user-attachments/assets/9e82a61c-4346-4579-b765-1aa877889531">

- No button for "Connected Wallet"
- Connected wallet should have a "open in etherscan" icon like the others
- I think we should drop the "copy" icon, it creates too much visual noise and is not that useful
- "Delegating to" should also have the "open in etherscan" icon

Delegating and revoking logic seems needs some attention. This is what happened after delegating:

![image](https://github.com/user-attachments/assets/afb4b0eb-69e9-4ebd-b40f-e88fd784667f)

This is what it looked like after I refreshed the page:

![image](https://github.com/user-attachments/assets/7ec16c26-bb28-43ce-87b2-0b6359a271ba)

I think the logical place to put the "Revoke" button is not on the "connected wallet", but in the place where you clicked "delegate". So I would convert the "Delegate" button into a "Revoke" button for the address that the connected address is delegating to. But in order to find it, the "delegating to" address (if any) should always take the second spot in the list, regardless of how it is sorted. Also, it should have the special label "Delegate address" with the etherscan icon next to it.

**Comment by luziusmeisser** [comment]
So in the end, it should look a little like this (disregard wrong color and bad positioning of the icons):

<img width="841" alt="image" src="https://github.com/user-attachments/assets/04378c00-3a81-4b29-8af7-99afb81a4928">

**Comment by luziusmeisser** [comment]
Bei der minter section sollte es einen Weg geben, die Transaction auf Etherscan zu finden. Dafür würde ich eine Spalte "Date" einführen, die auf etherscan linkt, zB: https://etherscan.io/tx/0x7f600bc46594c55abe0ca806f7e90b512f67597c0cce71e3a38533a7c48331e3

<img width="846" alt="image" src="https://github.com/user-attachments/assets/75bae0d6-21ca-44ff-b97c-3abc3c539e46">

Die Buttons, die zur Zeit disabled sind, würde ich gar nicht zeigen. Es gibt ja nichts, das man tun kann, um diese wieder zu enablen. Bei "Passed" und "Vetoed" habe ich die Farben rausgenommen. Wir sollten rot nur dann verwenden, wenn die Aufmerksamkeit des Benutzer erforderlich ist, um eine Gefahr oder einen Fehler abzuwenden.

**Comment by luziusmeisser** [comment]
The proposals section needs some rework. I would try to focus on the key variables here and place a link to the position so all the rest of the variables can be inspected. The link to the position would go to for example /monitoring/0x9057509C6DF28c50b3B4D142c44BAEEe23F22Fc7 .

How about the following:

<img width="870" alt="image" src="https://github.com/user-attachments/assets/60b1c56e-934f-4e44-a694-961c1a8933f3">

0. Add a row "Address"  after "collateral" that shows the position address and that sends the user to "/monitoring/0x9057509C6DF28c50b3B4D142c44BAEEe23F22Fc7" when clicking on it.
1. Use the full name for the type.
2. Remove initial size, initial price, and initial LTV. If the price is wrong, it should be challenged on the monitoring page
3. In order to not have too many columns, it might make sense to group the information as follows:

Address + Owner, Collateral, Limit + Reserve, Interest + Maturity, Time Left + Auction duration, Action.

**Comment by luziusmeisser** [comment]
Furthermore, we should make sure to use consistent font sizes across all tables.

<img width="935" alt="image" src="https://github.com/user-attachments/assets/913325b2-4af3-41f3-9c9a-2f03722642a8">

**Comment by AndreasFC94** [comment]
Under New Positions, we could probably lift up the "Action" text to fit into the same row as the other main headers, and change the font accordingly. 

![image](https://github.com/user-attachments/assets/d4e02ebe-fe76-4e55-b969-948f49b57d3b)

I think it might be best to implement these changes, and then we can take another look, since there are quite a few changes already.

**Comment by samclassix** [comment]
Ready for review.

# What i discovered in the voters table

The table data comes from hooks not a state, if you do a tx like "delegate" or "revoke", changes won't trigger a react re-render of components.

```
import { useFPSHolders } from "@hooks";
import { useVotingPowers } from "@hooks";
...
const fpsHolders = useFPSHolders();
const votingPowersHook = useVotingPowers(fpsHolders.holders);
```

React will not re-render if state changes, because its a hook and must stay "unconditional" under react components.

Basically, what i did the last months with the app is, to reduce or exclude hooks and rewrote them via a redux state coming from the api. Which gives each property of the state similar abilities like a "useState" side-effect. This is achievable by using the "useSelector" to reach a state from the redux store. React will re-render any changes from the state automatically. 

# What i could do

- include the votingPower mapping in the api
- fetch ponder indexing
- prepare mapping and calculations at the api service layer
- export "ready to use" state with an Endpoint from the api
- include votingPower as a state in redux
- exclude the use of hooks and rely on redux state

**Comment by samclassix** [comment]
# Not connected
![Screenshot 2024-09-02 at 9 29 23 AM](https://github.com/user-attachments/assets/2859be2a-e6c5-4693-b3ed-1725f19dad37)

# Connected Wallet, no delegation
![Screenshot 2024-09-02 at 9 29 52 AM](https://github.com/user-attachments/assets/de2eea70-e7e8-40e5-92d3-249b9069d72e)

# Connected Wallet, with delegation
![Screenshot 2024-09-02 at 9 28 41 AM](https://github.com/user-attachments/assets/8de10925-2c66-4f84-938e-ecd7500dc9e4)

**Comment by luziusmeisser** [comment]
I tend to leave the logic as it is. Mapping the voting power live in the backend is not trivial, as the voting power of every token holder is slightly changing with every block.

**Comment by luziusmeisser** [comment]
Even when the wallet is not connected, we sohuld show the original button labels like "Delegate" and not "Connect Wallet". But the behavior when clicking the button should still be a prompt to connect the wallet, if it is not yet connected.

**Comment by luziusmeisser** [comment]
It would be great if this area would be clickable too:
![image](https://github.com/user-attachments/assets/37cbd131-b443-4a58-bfc1-be52964325bd)

**Comment by luziusmeisser** [comment]
There should be some distance between the title and the text. Also, the text should be in a toned down color, like the second title in the table.

![image](https://github.com/user-attachments/assets/e8dd13b7-c8e1-4338-95f9-16b4ac188745)
